Saldo = 500
PRIMO_MESE = Saldo
SECONDO_MESE = round((PRIMO_MESE - 5) + (PRIMO_MESE * 2)/100)
TERZO_MESE = round((SECONDO_MESE - 5) + (SECONDO_MESE * 2)/100)
print("PRIMO MESE:",PRIMO_MESE)
print("SECONDO MESE:",SECONDO_MESE)
print("TERZO MESE:",TERZO_MESE, end="")
